package jframe;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author tina
 * @author stsof
 */
//Page that displays the main menu where the admin can access all the other pages
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
	DefaultTableModel model;
	
	Color blue = new java.awt.Color(22, 54, 150);
	Color ligthB = new java.awt.Color(242, 238, 226);
	Color mediumB = new java.awt.Color(240, 227, 186);
	Color darkB = new java.awt.Color(203, 187, 139);
	
    public HomePage() {
    	setAlwaysOnTop(true);
        initComponents();
        setBookDetailsToTable();
        setReadersDetailsToTable();
        setNumbersToLabels();
    }
    
    //Insert Book Details into the Table
    public void setBookDetailsToTable() {
    	DatabaseBook dbB = new DatabaseBook();
    	for(Book book : dbB.selectAllBook()) {
    		Object[] bk = book.bookToVector2(book);
    		model =(DefaultTableModel) tbl_bookDetails.getModel();
            model.addRow(bk);
    	} 	
    }
    //Insert Reader Details into the Table
    public void setReadersDetailsToTable(){
    	DatabaseReader dbR = new DatabaseReader();
    	for(User use : dbR.selectAllReaders()) {
    		Object[] user = use.userToVector(use);
    		model =(DefaultTableModel) tbl_readerDetails.getModel();
            model.addRow(user);	
    	}
    }
    //Displays the total number of readers, books and borrowings
    public void setNumbersToLabels(){
        
        Statement st = null;
        ResultSet rs = null;

        
        try {
            Connection con = DBConnection.getConnection();
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, 
            		   ResultSet.CONCUR_READ_ONLY);
             rs = st.executeQuery("select * from book");
              rs.last();
              int numberOfRows3 = rs.getRow();
              rs.beforeFirst();
              lbl_noOfBooks.setText(Integer.toString(numberOfRows3));
              
              rs = st.executeQuery("select * from readers");
              rs.last();
              int numberOfRows2 = rs.getRow();
              rs.beforeFirst();
              lbl_noOfReaders.setText(Integer.toString(numberOfRows2));
              
               rs = st.executeQuery("select * from borrowing");
              rs.last();
              int numberOfRows1 = rs.getRow();
              rs.beforeFirst();
              lbl_noOfBorrowedBooks.setText(Integer.toString(numberOfRows1));
              
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbl_noOfReaders = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_noOfBooks = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_readerDetails = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bookDetails = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_noOfBorrowedBooks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(blue);
        jPanel2.setPreferredSize(new java.awt.Dimension(1900, 70));

        jLabel1.setIcon(new ImageIcon(HomePage.class.getResource("/adminIcons/icons8_Library_32px.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Alice's Adventures In Javaland ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel24, GroupLayout.PREFERRED_SIZE, 362, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 929, Short.MAX_VALUE)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        			.addGap(489)
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(Alignment.LEADING, jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel3)
        					.addComponent(jLabel24)
        					.addComponent(jLabel2)))
        			.addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel5.setBackground(ligthB);

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, darkB));
        jPanel6.setMinimumSize(new java.awt.Dimension(260, 140));

        lbl_noOfReaders.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        lbl_noOfReaders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        lbl_noOfReaders.setText("10");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
        			.addContainerGap(82, Short.MAX_VALUE)
        			.addComponent(lbl_noOfReaders, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
        			.addGap(62))
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(lbl_noOfReaders)
        			.addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6.setLayout(jPanel6Layout);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel12.setText("Book Details");

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel16.setText("Number Of Books");

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, darkB));
        jPanel7.setMinimumSize(new java.awt.Dimension(260, 140));

        lbl_noOfBooks.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        lbl_noOfBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lbl_noOfBooks.setText("10");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lbl_noOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_noOfBooks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel18.setText("Number Of Borrowed Books");

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, darkB));
        jPanel8.setMinimumSize(new java.awt.Dimension(260, 140));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        jLabel19.setText("10");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_readerDetails.setBackground(mediumB);
        tbl_readerDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        tbl_readerDetails.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        tbl_readerDetails.setForeground(blue);
        tbl_readerDetails.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"Reader ID", "Name", "Contact"
        	}
        ));
        tbl_readerDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_readerDetails.setGridColor(blue);
        tbl_readerDetails.setRowHeight(30);
        tbl_readerDetails.setRowMargin(5);
        tbl_readerDetails.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_readerDetails.setSelectionForeground(blue);
        jScrollPane1.setViewportView(tbl_readerDetails);

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel20.setText("Number Of Readers");

        tbl_bookDetails.setBackground(mediumB);
        tbl_bookDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        tbl_bookDetails.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        tbl_bookDetails.setForeground(blue);
        tbl_bookDetails.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"Book ID", "Name", "Author", "Quantity", "Genre"
        	}
        ));
        tbl_bookDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_bookDetails.setGridColor(blue);
        tbl_bookDetails.setRowHeight(30);
        tbl_bookDetails.setRowMargin(5);
        tbl_bookDetails.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_bookDetails.setSelectionForeground(blue);
        jScrollPane2.setViewportView(tbl_bookDetails);

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel21.setText("Reader Details");

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel23.setText("Borrowed Books");

        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, darkB));
        jPanel9.setMinimumSize(new java.awt.Dimension(260, 140));

        lbl_noOfBorrowedBooks.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        lbl_noOfBorrowedBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        lbl_noOfBorrowedBooks.setText("10");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lbl_noOfBorrowedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_noOfBorrowedBooks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel7.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		ManageReaders reader = new ManageReaders();
                reader.setVisible(true);
                dispose();}
        });
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel9.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		ReturnBook book = new ReturnBook();
                book.setVisible(true);
                dispose();
        	}
        });
        jLabel10 = new javax.swing.JLabel();
        jLabel10.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
                BookBorrowing book = new BookBorrowing();
                book.setVisible(true);
                dispose();
        	}
        });
        jLabel11 = new javax.swing.JLabel();
        jLabel11.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		JFrame jf=new JFrame();
        		jf.setAlwaysOnTop(true);
        		int dialogButton = JOptionPane.YES_NO_OPTION;
        		int input = JOptionPane.showConfirmDialog (jf, "Are you sure you want to logout?","Logout",dialogButton);
        		if(input == JOptionPane.YES_OPTION){
                    LoginPage login = new LoginPage();
                    login.setVisible(true);
                    dispose();
        		}
        		if(input == JOptionPane.NO_OPTION){
        			HomePage home = new HomePage();
                    home.setVisible(true);
                    dispose();
      		}
        	}
        });
        jLabel13 = new javax.swing.JLabel();
        jLabel13.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		ViewRecords record = new ViewRecords();
                record.setVisible(true);
                dispose();
        	}
        });
        jLabel14 = new javax.swing.JLabel();
        jLabel14.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		BorrowedBooks book = new BorrowedBooks();
                book.setVisible(true);
                dispose();
        	}
        });
        
                jPanel3.setBackground(mediumB);
                jPanel3.setPreferredSize(new java.awt.Dimension(200, 947));
                
                        jPanel4.setBackground(darkB);
                        jPanel4.setMinimumSize(new java.awt.Dimension(30, 100));
                        
                                jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
                                jLabel5.setForeground(blue);
                                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
                                jLabel5.setText("Home Page");
                                
                                        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                                        jPanel4Layout.setHorizontalGroup(
                                        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
                                        		.addGroup(Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        			.addContainerGap()
                                        			.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                        			.addContainerGap(66, Short.MAX_VALUE))
                                        );
                                        jPanel4Layout.setVerticalGroup(
                                        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
                                        		.addGroup(jPanel4Layout.createSequentialGroup()
                                        			.addContainerGap()
                                        			.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        );
                                        jPanel4.setLayout(jPanel4Layout);
                                        
                                                jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
                                                jLabel6.setForeground(blue);
                                                jLabel6.setText("Features");
                                                
                                                        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
                                                        jLabel7.setForeground(blue);
                                                        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
                                                        jLabel7.setText("Manage Readers");
                                                        
                                                                jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
                                                                jLabel8.setForeground(blue);
                                                                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
                                                                jLabel8.setText("Manage Books");
                                                                jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
                                                                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                                        jLabel8MouseClicked(evt);
                                                                    }
                                                                });
                                                                
                                                                        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
                                                                        jLabel9.setForeground(blue);
                                                                        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
                                                                        jLabel9.setText("Return Book");
                                                                        
                                                                                jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
                                                                                jLabel10.setForeground(blue);
                                                                                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
                                                                                jLabel10.setText("Book Borrowing");
                                                                                
                                                                                        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
                                                                                        jLabel11.setForeground(blue);
                                                                                        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px.png"))); // NOI18N
                                                                                        jLabel11.setText("Logout");
                                                                                        
                                                                                                jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
                                                                                                jLabel13.setForeground(blue);
                                                                                                jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
                                                                                                jLabel13.setText("View Records");
                                                                                                
                                                                                                        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
                                                                                                        jLabel14.setForeground(blue);
                                                                                                        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
                                                                                                        jLabel14.setText("Borrowed Books");
                                                                                                        
                                                                                                                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                                                                                                                jPanel3Layout.setHorizontalGroup(
                                                                                                                	jPanel3Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                		.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                		.addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                                			.addContainerGap(20, Short.MAX_VALUE)
                                                                                                                			.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addContainerGap())
                                                                                                                		.addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                                			.addContainerGap()
                                                                                                                			.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addContainerGap(66, Short.MAX_VALUE))
                                                                                                                		.addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                                			.addContainerGap()
                                                                                                                			.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addContainerGap(20, Short.MAX_VALUE))
                                                                                                                		.addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                                			.addContainerGap()
                                                                                                                			.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addContainerGap(20, Short.MAX_VALUE))
                                                                                                                		.addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                                			.addContainerGap()
                                                                                                                			.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addContainerGap(20, Short.MAX_VALUE))
                                                                                                                		.addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                                			.addContainerGap()
                                                                                                                			.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                                                		.addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                                			.addContainerGap()
                                                                                                                			.addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addContainerGap(20, Short.MAX_VALUE))
                                                                                                                		.addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                                			.addContainerGap()
                                                                                                                			.addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addContainerGap(20, Short.MAX_VALUE))
                                                                                                                );
                                                                                                                jPanel3Layout.setVerticalGroup(
                                                                                                                	jPanel3Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                		.addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                                			.addGap(21)
                                                                                                                			.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addGap(18)
                                                                                                                			.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addPreferredGap(ComponentPlacement.UNRELATED)
                                                                                                                			.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addGap(18)
                                                                                                                			.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addGap(32)
                                                                                                                			.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addGap(27)
                                                                                                                			.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addGap(29)
                                                                                                                			.addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addGap(35)
                                                                                                                			.addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                                                                                                			.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                                                                                                			.addGap(28))
                                                                                                                );
                                                                                                                jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addGap(80)
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 930, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 930, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel21, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE))
        					.addGap(202))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel20, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE))
        					.addGap(42)
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE))
        					.addGap(38)
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jPanel9, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addComponent(jLabel23, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, 47, Short.MAX_VALUE)))))
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(224)
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel18, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addGap(36)
        							.addComponent(jLabel18)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        							.addGap(13))
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addContainerGap()
        							.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel5Layout.createSequentialGroup()
        									.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
        										.addComponent(jLabel20)
        										.addComponent(jLabel16))
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addGroup(jPanel5Layout.createParallelGroup(Alignment.TRAILING)
        										.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        										.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)))
        								.addGroup(jPanel5Layout.createSequentialGroup()
        									.addComponent(jLabel23)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(jPanel9, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)))
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel21)
        							.addPreferredGap(ComponentPlacement.RELATED)))
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
        					.addGap(13)
        					.addComponent(jLabel12)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 675, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5.setLayout(jPanel5Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 2030, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        setSize(new java.awt.Dimension(1414, 751));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        ManageBooks books = new ManageBooks();
        books.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
                JFrame jFrame = new JFrame();
				jFrame.setAlwaysOnTop(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel lbl_noOfReaders;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel lbl_noOfBooks;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel lbl_noOfBorrowedBooks;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_readerDetails;
    private javax.swing.JTable tbl_bookDetails;
}

