 /* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package jframe;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import rojerusan.RSButtonMetro;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

import rojeru_san.componentes.RSDateChooser;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextField;
import javax.swing.JLayeredPane;

/**
 *
* @author tina
 * @author stsof
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
	
	
    public LoginPage() {
    	setAlwaysOnTop(true);
        initComponents();
        wrongEmail.setVisible(false);
        wrongPass.setVisible(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(22, 54, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(1900, 70));
        
        //ClassLoader c = Thread.currentThread().getContextClassLoader();
        //URL res = c.getResource("/adminIcons/icons8_Library_32px.png");

        jLabel1.setIcon(new ImageIcon(LoginPage.class.getResource("/adminIcons/icons8_Library_32px.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Alice's Adventures In Javaland ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel24, GroupLayout.PREFERRED_SIZE, 419, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 891, Short.MAX_VALUE)
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel3)
        				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jLabel24)))
        			.addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel5.setBackground(new java.awt.Color(242, 238, 226));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 60)); // NOI18N
        jLabel21.setText("LOGIN");
        
        JButton loginButton = new JButton("Login");
        loginButton.setForeground(Color.WHITE);
        loginButton.setBackground(new java.awt.Color(22, 54, 150));
        loginButton.setOpaque(true);
        loginButton.setBorder(null);
        
        loginButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		try {
        		
        			DatabaseAdmin dbAdmin = new DatabaseAdmin();
        			
	        		String password = passValue. getText();
	        		String email = emailValue.getText();
	        		if(!dbAdmin.registedAdmin(email)) {
	        			wrongEmail.setVisible(true);
	        		}else {
		        		if (dbAdmin.checkLogin(email, password)) {
		        			HomePage home = new HomePage();
		                    home.setVisible(true);
		                    dispose();
		        			
		        		} else {
		        			wrongPass.setVisible(true);
		        			btn_SignIn.setVisible(false);
		        			lblNewLabel.setVisible(false);
		        			lblNewLabel_1.setVisible(false);
		        		}
	        		}
	        		
        		
	    		} catch (SQLException ex) {
	    			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	    		}
        		
        		
        		
        	}
        });
        
        btn_SignIn = new JButton("here");
        btn_SignIn.setForeground(Color.RED);
        btn_SignIn.setBackground(new java.awt.Color(242, 238, 226));
        btn_SignIn.setOpaque(true);
        btn_SignIn.setBorder(null);
        
        btn_SignIn.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		SignPage home = new SignPage();
                home.setVisible(true);
                dispose();
        		
        	}
        });
        
        emailValue = new JTextField();
        emailValue.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		emailValue.setText("");
        	}
        });
        emailValue.setColumns(10);
        emailValue.setBackground(new Color(240, 227, 186));   
        emailValue.setText("email");
        emailValue.setForeground(new Color(22, 54, 150));
        emailValue.setFont(new Font("Dialog", Font.BOLD, 18));
        emailValue.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		emailValue.setText("");
        	}
        });
        
        wrongEmail = new JLabel("The email you entered is not connected to an account.");
        wrongEmail.setForeground(Color.RED);
        
        wrongPass = new JLabel("The password you entered is incorrect.");
        wrongPass.setForeground(Color.RED);
        
        lblNewLabel = new JLabel("Not a member yet?\n");
        
        lblNewLabel_1 = new JLabel("Sign up");
        
        JLayeredPane layeredPane = new JLayeredPane();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGap(502)
        					.addComponent(jLabel21, GroupLayout.PREFERRED_SIZE, 226, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGap(438)
        					.addComponent(wrongEmail))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGap(488)
        					.addComponent(wrongPass))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGap(413)
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(layeredPane, GroupLayout.PREFERRED_SIZE, 414, GroupLayout.PREFERRED_SIZE)
        						.addComponent(emailValue, GroupLayout.PREFERRED_SIZE, 396, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGap(580)
        					.addComponent(loginButton, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGap(558)
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addGap(6)
        							.addComponent(lblNewLabel_1)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(btn_SignIn))
        						.addComponent(lblNewLabel))))
        			.addContainerGap(583, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addGap(97)
        			.addComponent(jLabel21)
        			.addGap(59)
        			.addComponent(emailValue, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(layeredPane, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(loginButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(lblNewLabel)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel_1)
        				.addComponent(btn_SignIn))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(wrongPass, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(wrongEmail)
        			.addGap(133))
        );
        
        final JLabel passLabel = new JLabel("password");
        passLabel.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		passLabel.setText("");
        	}
        });
        passLabel.setBounds(6, 18, 101, 22);
        layeredPane.add(passLabel);
        passLabel.setForeground(new Color(22, 54, 150));
        passLabel.setFont(new Font("Dialog", Font.BOLD, 18));
        
        passValue = new JPasswordField();
        passValue.setBounds(0, 6, 396, 50);
        passValue.setFont(new Font("Dialog", Font.BOLD, 18));
        
        
        layeredPane.add(passValue);
        passValue.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		passLabel.setText("");
        	}
        });
        passValue.setColumns(10);
        passValue.setBackground(new Color(240, 227, 186));   
        passValue.setForeground(new Color(22, 54, 150));
        jPanel5.setLayout(jPanel5Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(jPanel2, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
        				.addComponent(jPanel5, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        setSize(new java.awt.Dimension(1414, 751));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) throws SQLException, ParseException {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        ManageBooks books = new ManageBooks();
        books.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        BookBorrowing book = new BookBorrowing();
        book.setVisible(true);
        dispose();
    }  
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
                JFrame jFrame = new JFrame();
				jFrame.setAlwaysOnTop(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private JTextField emailValue;
    private JTextField passValue;
    private JButton btn_SignIn;
    private JLabel wrongEmail;
    private JLabel wrongPass;
    private JLabel lblNewLabel;
    private JLabel lblNewLabel_1;
}
