 /* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;


/**
 *
* @author tina
 * @author stsof
 */
public class ManageReaders extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
	DefaultTableModel model;
	
	
	Color blue = new java.awt.Color(22, 54, 150);
	Color ligthB = new java.awt.Color(242, 238, 226);
	Color mediumB = new java.awt.Color(240, 227, 186);
	Color darkB = new java.awt.Color(203, 187, 139);
	Color white = new java.awt.Color(255, 255, 255);
	
	
    public ManageReaders() {
        initComponents();
        setReadersDetailsToTable();
    }
    
    
    //to set the reader details into the table
    public void setReadersDetailsToTable(){
    	DatabaseReader dbR = new DatabaseReader();
    	for(User use : dbR.selectAllReaders()) {
    		Object[] user = use.userToVector(use);
    		model =(DefaultTableModel) tbl_readersDetails.getModel();
            model.addRow(user);	
    	}
    }
    
    //method to clear table
    
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_readersDetails.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_readerID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_readerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_phoneNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_readersDetails = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1358, 702));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1358, 702));

        jPanel1.setBackground(blue);
        
        jPanel3.setBackground(ligthB);

        jScrollPane2.setBackground(darkB);
        
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel1.setForeground(white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N

        txt_readerID.setBackground(blue);
        txt_readerID.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_readerID.setForeground(white);
        txt_readerID.setToolTipText("");
        txt_readerID.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, white));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel3.setForeground(white);
        jLabel3.setText("Reader ID:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel4.setForeground(white);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N

        txt_readerName.setBackground(blue);
        txt_readerName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_readerName.setForeground(white);
        txt_readerName.setToolTipText("");
        txt_readerName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, white));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel5.setForeground(white);
        jLabel5.setText("Reader Name:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel6.setForeground(white);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N

        txt_email.setBackground(blue);
        txt_email.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_email.setForeground(white);
        txt_email.setToolTipText("");
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, white));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel7.setForeground(white);
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel8.setForeground(white);
        jLabel8.setIcon(new ImageIcon(ManageReaders.class.getResource("/icons/icons8_Google_Mobile_50px.png"))); // NOI18N

        txt_phoneNumber.setBackground(blue);
        txt_phoneNumber.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_phoneNumber.setForeground(white);
        txt_phoneNumber.setToolTipText("");
        txt_phoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, white));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel9.setForeground(white);
        jLabel9.setText("Phone Number:");

        jButton1.setBackground(darkB);
        jButton1.setOpaque(true);
        jButton1.setBorder(null);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(blue);
        jButton1.setText("Update");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, darkB));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton3.setBackground(darkB);
        jButton3.setOpaque(true);
        jButton3.setBorder(null);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(blue);
        jButton3.setText("Delete");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, darkB));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLabel2 = new javax.swing.JLabel();
        
                jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
                jLabel2.setForeground(darkB);
                jLabel2.setIcon(new ImageIcon(ManageReaders.class.getResource("/AddNewBookIcons/backIconC.png"))); // NOI18N
                jLabel2.setText("Back");
                jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel2MouseClicked(evt);
                    }
                });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        						.addGap(6))
        					.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        						.addContainerGap()
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE))
        						.addGap(27)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(31)
        					.addComponent(jLabel8)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        					.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        						.addComponent(txt_email, GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        						.addContainerGap())
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addGap(2)
        								.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
        							.addComponent(txt_readerID, GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        						.addGap(63))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
        						.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
        						.addGap(55))
        					.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        						.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 141, GroupLayout.PREFERRED_SIZE)
        						.addContainerGap())
        					.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 177, GroupLayout.PREFERRED_SIZE)
        							.addComponent(txt_readerName, GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        						.addContainerGap()))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(txt_phoneNumber, GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        					.addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(12)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(txt_readerID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(46)
        					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(txt_readerName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        					.addGap(42)
        					.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)))
        			.addGap(24)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(20)
        					.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        					.addGap(9)
        					.addComponent(txt_email, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(43)
        					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)))
        			.addGap(46)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        					.addGap(22)
        					.addComponent(txt_phoneNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jLabel8))
        			.addPreferredGap(ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE))
        			.addGap(48))
        );
        jPanel1.setLayout(jPanel1Layout);

        txt_readerID.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(white);

        tbl_readersDetails.setBackground(darkB);
        tbl_readersDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        tbl_readersDetails.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        tbl_readersDetails.setForeground(blue);
        tbl_readersDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reader ID", "Name", "Email", "Phone Number", "No Of Borrowings"
            }
        ));
        tbl_readersDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_readersDetails.setGridColor(blue);
        tbl_readersDetails.setRowHeight(30);
        tbl_readersDetails.setRowMargin(5);
        tbl_readersDetails.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_readersDetails.setSelectionForeground(blue);
        tbl_readersDetails.setShowGrid(true);
        tbl_readersDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bookDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_bookDetailsMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_readersDetails);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel11.setForeground(blue);
        jLabel11.setIcon(new ImageIcon(ManageReaders.class.getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        jLabel11.setText("Manage Readers");
        jLabel10 = new javax.swing.JLabel();
        
                jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
                jLabel10.setForeground(blue);
                jLabel10.setText("X");
                jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel10MouseClicked(evt);
                    }
                });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        					.addComponent(jLabel10, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        					.addGroup(jPanel3Layout.createSequentialGroup()
        						.addGap(19)
        						.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 930, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGap(318)
        					.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 287, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(jLabel10)
        			.addGap(20)
        			.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addGap(96)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
        			.addGap(0, 349, Short.MAX_VALUE))
        );
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 439, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 977, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        		.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        setSize(new java.awt.Dimension(1414, 751));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	DatabaseReader dbR = new DatabaseReader();
        if(dbR.updateReader(txt_readerName.getText(),txt_email.getText(), Integer.parseInt(txt_phoneNumber.getText()),  Integer.parseInt(txt_readerID.getText()))){
            JOptionPane.showMessageDialog(this, "Reader Updated");
            clearTable();
            setReadersDetailsToTable();
        }
        else{
            JOptionPane.showMessageDialog(this, "Reader Update Unsuccessful");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
    	DatabaseReader dbR = new DatabaseReader();
        // TODO add your handling code here:
        if(dbR.deleteReader(Integer.parseInt(txt_readerID.getText()))){
            JOptionPane.showMessageDialog(this, "Reader Deleted");
            clearTable();
            setReadersDetailsToTable();
        }
        else{
            JOptionPane.showMessageDialog(this, "Reader Deletion Unsuccessful");
        }
    } 

    private void tbl_bookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookDetailsMouseClicked
        // TODO add your handling code here:
        int rowNumber = tbl_readersDetails.getSelectedRow();
    	TableModel model = tbl_readersDetails.getModel();
    	
    	txt_readerID.setText(model.getValueAt(rowNumber, 0).toString());
    	txt_readerName.setText( model.getValueAt(rowNumber, 1).toString());
    	txt_email.setText( model.getValueAt(rowNumber, 2).toString());
    	txt_phoneNumber.setText( model.getValueAt(rowNumber,3).toString());
  
    	
    }//GEN-LAST:event_tbl_bookDetailsMouseClicked

    private void tbl_bookDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookDetailsMouseEntered

    	
    }//GEN-LAST:event_tbl_bookDetailsMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReaders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_readersDetails;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_readerName;
    private javax.swing.JTextField txt_readerID;
    private javax.swing.JTextField txt_phoneNumber;
}
