/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.ImageIcon;


/**
 *
* @author tina
 * @author stsof
 */
public class ManageBooks extends javax.swing.JFrame {

	Color blue = new java.awt.Color(22, 54, 150);
	Color ligthB = new java.awt.Color(242, 238, 226);
	Color mediumB = new java.awt.Color(240, 227, 186);
	Color darkB = new java.awt.Color(203, 187, 139);
	
    /**
     * Creates new form ManageBooks
     */
	
	DefaultTableModel model;
	
    public ManageBooks() {
        initComponents();
        setBookDetailsToTable();
    }
    //Insert Book Details into the Table
    public void setBookDetailsToTable() {
    	DatabaseBook dbB = new DatabaseBook();
    	for(Book book : dbB.selectAllBook()) {
    		Object[] bk = book.bookToVector(book);
    		model =(DefaultTableModel) tbl_bookDetails.getModel();
            model.addRow(bk);
    	} 	
    }
    	
 
    //Clear Data of the Table
    public void clearTable() {
    	DefaultTableModel model = (DefaultTableModel) tbl_bookDetails.getModel();
    	model.setRowCount(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_bookReference = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_bookName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_authorName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bookDetails = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtFiel_genre = new javax.swing.JTextField();
        
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1358, 702));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1358, 702));

        jPanel1.setBackground(blue);

        txt_bookReference.setBackground(blue);
        txt_bookReference.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_bookReference.setForeground(new java.awt.Color(255, 255, 255));
        txt_bookReference.setToolTipText("");
        txt_bookReference.setSize(10, 10);
        txt_bookReference.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");

        txt_bookName.setBackground(blue);
        txt_bookName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_bookName.setForeground(new java.awt.Color(255, 255, 255));
        txt_bookName.setToolTipText("");
        txt_bookName.setSize(10, 10);
        txt_bookName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");

        txt_authorName.setBackground(blue);
        txt_authorName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_authorName.setForeground(new java.awt.Color(255, 255, 255));
        txt_authorName.setToolTipText("");
        txt_authorName.setSize(10, 10);
        txt_authorName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Author");

        txt_quantity.setBackground(blue);
        txt_quantity.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_quantity.setForeground(new java.awt.Color(255, 255, 255));
        txt_quantity.setToolTipText("");
        txt_quantity.setSize(10, 10);
        txt_quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity");

        jButton1.setBackground(darkB);
        jButton1.setOpaque(true);
        jButton1.setBorder(null);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(blue);
        jButton1.setText("Update");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, darkB));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(darkB);
        jButton2.setOpaque(true);
        jButton2.setBorder(null);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(blue);
        jButton2.setText("Add");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, darkB));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton3.setBackground(darkB);
        jButton3.setOpaque(true);
        jButton3.setBorder(null);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(blue);
        jButton3.setText("Delete");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, darkB));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        JLabel lblNewLabel = new JLabel("Tag");
        lblNewLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        lblNewLabel.setForeground(new java.awt.Color(255, 255, 255));
        

        txtFiel_genre.setBackground(blue);
        txtFiel_genre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txtFiel_genre.setForeground(new java.awt.Color(255, 255, 255));
        txtFiel_genre.setToolTipText("");
        txtFiel_genre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        jLabel2 = new javax.swing.JLabel();
        
                jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
                jLabel2.setForeground(darkB);
                jLabel2.setIcon(new ImageIcon(ManageBooks.class.getResource("/AddNewBookIcons/backIconC.png"))); // NOI18N
                jLabel2.setText("Back");
                jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel2MouseClicked(evt);
                    }
                });
        
        lblNewLabel_1 = new JLabel("Publication");
        lblNewLabel_1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        lblNewLabel_1.setForeground(new java.awt.Color(255, 255, 255));
        
        TextField_publication = new JTextField();
        TextField_publication.setBackground(blue);
        TextField_publication.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        TextField_publication.setForeground(new java.awt.Color(255, 255, 255));
        TextField_publication.setToolTipText("");
        TextField_publication.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        
        JLabel lblNewLabel_2 = new JLabel("Type");
        lblNewLabel_2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        lblNewLabel_2.setForeground(new java.awt.Color(255, 255, 255));
        
        textField_type = new JTextField();
        textField_type.setBackground(blue);
        textField_type.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        textField_type.setForeground(new java.awt.Color(255, 255, 255));
        textField_type.setToolTipText("");
        textField_type.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        
        JLabel lblNewLabel_3 = new JLabel("URL");
        lblNewLabel_3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        lblNewLabel_3.setForeground(new java.awt.Color(255, 255, 255));
        
        textField_URL = new JTextField();
        textField_URL.setBackground(blue);
        textField_URL.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        textField_URL.setForeground(new java.awt.Color(255, 255, 255));
        textField_URL.setToolTipText("");
        textField_URL.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(38)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblNewLabel_1)
        						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblNewLabel)
        						.addComponent(lblNewLabel_2)
        						.addComponent(lblNewLabel_3)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(jLabel7, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel5, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
        						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(9)
        							.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(txt_authorName, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        								.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        									.addGap(27)
        									.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        									.addGap(39)
        									.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
        								.addComponent(textField_type, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        								.addComponent(textField_URL, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        								.addComponent(txt_bookName, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(txt_bookReference, GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        									.addGap(3)))
        							.addPreferredGap(ComponentPlacement.RELATED))
        						.addComponent(txt_quantity, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        						.addComponent(TextField_publication, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        						.addComponent(txtFiel_genre, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))))
        			.addGap(14))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(16)
        			.addComponent(jLabel2)
        			.addGap(77)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txt_bookReference, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txt_bookName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txt_authorName, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addGap(28)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel_1)
        				.addComponent(TextField_publication, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(27)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel)
        				.addComponent(txtFiel_genre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txt_quantity, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(31)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel_2)
        				.addComponent(textField_type, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addGap(30)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel_3)
        				.addComponent(textField_URL, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE))
        			.addGap(6))
        );
        jPanel1.setLayout(jPanel1Layout);

        txt_bookReference.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tbl_bookDetails.setBackground(mediumB);
        tbl_bookDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        tbl_bookDetails.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        tbl_bookDetails.setForeground(blue);
        tbl_bookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Name", "Author", "Publication", "Quantity", "Genre", "Type"
            }
        ));
        tbl_bookDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_bookDetails.setGridColor(blue);
        tbl_bookDetails.setRowHeight(30);
        tbl_bookDetails.setRowMargin(5);
        tbl_bookDetails.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_bookDetails.setSelectionForeground(blue);
        tbl_bookDetails.setShowGrid(true);
        tbl_bookDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bookDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_bookDetailsMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_bookDetails);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel11.setForeground(blue);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jLabel11.setText("Manage Books");
        jLabel10 = new javax.swing.JLabel();
        
                jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
                jLabel10.setForeground(blue);
                jLabel10.setText("X");
                jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel10MouseClicked(evt);
                    }
                });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap(19, Short.MAX_VALUE)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 930, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 248, GroupLayout.PREFERRED_SIZE)
        					.addGap(288)
        					.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGap(46)
        					.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGap(26)
        					.addComponent(jLabel10)))
        			.addGap(55)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 478, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 433, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        		.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        setSize(new java.awt.Dimension(1414, 751));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	DatabaseBook dbB = new DatabaseBook();
    	// TODO add your handling code here:
        if(dbB.updateBook(Integer.parseInt(txt_bookReference.getText()),txt_bookName.getText(),txt_authorName.getText(), 
        		Integer.parseInt(txt_quantity.getText()), txtFiel_genre.getText(),Integer.parseInt(TextField_publication.getText()),
        		textField_URL.getText(), textField_type.getText())){
            JOptionPane.showMessageDialog(this, "Book Updated");
            clearTable();
            setBookDetailsToTable();
        }
        else{
            JOptionPane.showMessageDialog(this, "Book Update Unsuccessful");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {  
    	DatabaseBook dbB = new DatabaseBook();
        // TODO add your handling code here:
    	if((!dbB.numberOrNot(TextField_publication.getText()))) {
    		JOptionPane.showMessageDialog(this, "Book Addition Unsuccessful");
    	}
    	if((!dbB.numberOrNot(txt_quantity.getText()))) {
    		JOptionPane.showMessageDialog(this, "Book Addition Unsuccessful");
    	}
    	if((!dbB.numberOrNot(txt_bookReference.getText()))) {
    		JOptionPane.showMessageDialog(this, "Book Addition Unsuccessful");
    	}
        if(dbB.addBook(Integer.parseInt(txt_bookReference.getText()),txt_bookName.getText(),txt_authorName.getText(), 
        		Integer.parseInt(txt_quantity.getText()), txtFiel_genre.getText(), Integer.parseInt(TextField_publication.getText()),
        		textField_URL.getText(), textField_type.getText())){
            JOptionPane.showMessageDialog(this, "Book Added");
            clearTable();
            setBookDetailsToTable();
        }
        else{
            JOptionPane.showMessageDialog(this, "Book Addition Unsuccessful");
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
    	DatabaseBook dbB = new DatabaseBook();
        // TODO add your handling code here:
        if(dbB.deleteBook(Integer.parseInt(txt_bookReference.getText()))){
            JOptionPane.showMessageDialog(this, "Book Deleted");
            clearTable();
            setBookDetailsToTable();
        }
        else{
            JOptionPane.showMessageDialog(this, "Book Deletion Unsuccessful");
        }
    } 

    private void tbl_bookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookDetailsMouseClicked
        // TODO add your handling code here:
        int rowNumber = tbl_bookDetails.getSelectedRow();
    	TableModel model = tbl_bookDetails.getModel();
    	int reference = Integer.parseUnsignedInt(model.getValueAt(rowNumber, 0).toString());
    	
    	DatabaseBook dbB = new DatabaseBook();
    	Book book = dbB.selectABook(reference);
    	
    	txt_bookReference.setText(String.valueOf(book.getReference()));
    	txt_bookName.setText( book.getName());
    	txt_authorName.setText( book.getAuthor());
    	textField_type.setText(book.typeBook(book.getType()));
    	txt_quantity.setText(String.valueOf(book.getQuantity()));
    	txtFiel_genre.setText( book.getTag());
    	TextField_publication.setText(String.valueOf(book.getPublication()));
    	textField_URL.setText(book.getUrl());
    	
    }//GEN-LAST:event_tbl_bookDetailsMouseClicked
    private void tbl_bookDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookDetailsMouseEntered

    	
    }//GEN-LAST:event_tbl_bookDetailsMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_bookDetails;
    private javax.swing.JTextField txt_authorName;
    private javax.swing.JTextField txt_bookName;
    private javax.swing.JTextField txt_bookReference;
    private javax.swing.JTextField txt_quantity;
    private JTextField txtFiel_genre;
    private JLabel lblNewLabel_1;
    private JTextField TextField_publication;
    private JTextField textField_type;
    private JTextField textField_URL;
}
