/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
import rojeru_san.componentes.RSDateChooser;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
* @author tina
 * @author stsof
 */
//Page that displays all the borrowings (returned or not returned)
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
    
    public boolean getBorrowingDetails() {
    	DatabaseBorrowing dbB = new DatabaseBorrowing();
    	lbl_Erro.setText("");
        int bookId = Integer.parseInt(txt_bookReference.getText());
        int readerId = Integer.parseInt(txt_readerID.getText());
        
        if(dbB.selectAllBorrowingType(bookId,readerId) != null) {
        	for(Borrowing borrow : dbB.selectAllBorrowingType(bookId,readerId)) {
        		
        		lbl_issueID.setText( String.valueOf(borrow.getId()));
                lbl_bookName.setText(borrow.getBook().getName());
                lbl_readerName.setText(borrow.getUser().getName());	
                lbl_issueDate.setText(borrow.getStartPeriod());
                lbl_dueDate.setText(borrow.getEndPeriod());
        	} 
        	return true;
        }else {
        	lbl_Erro.setText("No borrowing available");
        	return false;
        }
    	
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_bookReference = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_readerID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_readerName = new javax.swing.JLabel();
        lbl_issueID = new javax.swing.JLabel();
        lbl_issueDate = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1358, 702));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1358, 702));

        panel_main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(22, 54, 150));
        jLabel12.setText("Return Book");

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reader");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(22, 54, 150));
        jLabel7.setText("Enter Book ID:");

        txt_bookReference.setBackground(new java.awt.Color(203, 187, 139));
        txt_bookReference.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_bookReference.setForeground(new java.awt.Color(22, 54, 150));
        txt_bookReference.setToolTipText("");
        txt_bookReference.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 54, 150)));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(22, 54, 150));
        jLabel14.setText("Enter Reader ID:");

        txt_readerID.setBackground(new java.awt.Color(203, 187, 139));
        txt_readerID.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txt_readerID.setForeground(new java.awt.Color(22, 54, 150));
        txt_readerID.setToolTipText("");
        txt_readerID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 54, 150)));
        
        return_Button = new JButton("Borrowing");
        return_Button.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		returnMouseClicked(e);
        	}		
        });
        
        return_Button.setBackground(new java.awt.Color(203, 187, 139));
        return_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        return_Button.setForeground(new java.awt.Color(51, 51, 51));
        return_Button.setText("Return");
        return_Button.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(203, 187, 139)));
        return_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        

        JPanel jPanel3_1 = new JPanel();
        jPanel3_1.setPreferredSize(new Dimension(342, 5));
        jPanel3_1.setBackground(new java.awt.Color(22, 54, 150));
        GroupLayout gl_jPanel3_1 = new GroupLayout(jPanel3_1);
        gl_jPanel3_1.setHorizontalGroup(
        	gl_jPanel3_1.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 417, Short.MAX_VALUE)
        		.addGap(0, 342, Short.MAX_VALUE)
        );
        gl_jPanel3_1.setVerticalGroup(
        	gl_jPanel3_1.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 5, Short.MAX_VALUE)
        		.addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3_1.setLayout(gl_jPanel3_1);
        
        btnNewButton_1 = new JButton("New button");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		getBorrowingDetails();
        	}
        });
        btnNewButton_1.setBackground(new java.awt.Color(203, 187, 139));
        btnNewButton_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnNewButton_1.setForeground(new java.awt.Color(51, 51, 51));
        btnNewButton_1.setText("Find");
        btnNewButton_1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(203, 187, 139)));
        btnNewButton_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        
        lbl_Erro = new JLabel("");
        lbl_Erro.setForeground(Color.RED);
        lbl_Erro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 19)); // NOI18N
        
        jLabel10 = new JLabel();
        jLabel10.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		System.exit(0);
        	}
        });
        jLabel10.setText("X");
        jLabel10.setForeground(new Color(22, 54, 150));
        jLabel10.setFont(new Font("Yu Gothic UI Semilight", Font.BOLD, 36));

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_mainLayout.setHorizontalGroup(
        	panel_mainLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panel_mainLayout.createSequentialGroup()
        			.addGap(47)
        			.addComponent(jPanel3_1, GroupLayout.PREFERRED_SIZE, 417, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(57, Short.MAX_VALUE))
        		.addGroup(panel_mainLayout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(panel_mainLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(panel_mainLayout.createSequentialGroup()
        					.addComponent(jLabel14, GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        					.addContainerGap())
        				.addGroup(panel_mainLayout.createSequentialGroup()
        					.addGroup(panel_mainLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(panel_mainLayout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(txt_bookReference, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        							.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE))
        						.addGroup(panel_mainLayout.createSequentialGroup()
        							.addComponent(txt_readerID, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        							.addGap(39)
        							.addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)))
        					.addGap(231))
        				.addGroup(panel_mainLayout.createSequentialGroup()
        					.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
        					.addGap(148))
        				.addGroup(panel_mainLayout.createSequentialGroup()
        					.addGap(184)
        					.addGroup(panel_mainLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnNewButton_1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        						.addComponent(return_Button, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lbl_Erro))
        					.addGap(174))))
        		.addGroup(panel_mainLayout.createSequentialGroup()
        			.addContainerGap(464, Short.MAX_VALUE)
        			.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        			.addGap(18))
        );
        panel_mainLayout.setVerticalGroup(
        	panel_mainLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panel_mainLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        			.addGap(15)
        			.addComponent(jLabel12)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel3_1, GroupLayout.PREFERRED_SIZE, 5, GroupLayout.PREFERRED_SIZE)
        			.addGap(33)
        			.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(txt_bookReference, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(92)
        			.addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(panel_mainLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel13)
        				.addComponent(txt_readerID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(53)
        			.addComponent(lbl_Erro)
        			.addGap(38)
        			.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
        			.addComponent(return_Button, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        			.addGap(73))
        );
        panel_main.setLayout(panel_mainLayout);

        jPanel1.setBackground(new java.awt.Color(22, 54, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 608));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book ");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(342, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book Name:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Issue ID:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Issue Date:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reader Name:");

        lbl_readerName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        lbl_readerName.setForeground(new java.awt.Color(255, 255, 255));

        lbl_issueID.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        lbl_issueID.setForeground(new java.awt.Color(255, 255, 255));

        lbl_issueDate.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        lbl_issueDate.setForeground(new java.awt.Color(255, 255, 255));

        lbl_bookName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        lbl_bookName.setForeground(new java.awt.Color(255, 255, 255));
        
        JLabel lblDueDate = new JLabel();
        lblDueDate.setText("Due Date:");
        lblDueDate.setForeground(Color.WHITE);
        lblDueDate.setFont(new Font("Yu Gothic UI Semilight", Font.PLAIN, 20));
        
        lbl_dueDate = new JLabel();
        lbl_dueDate.setForeground(Color.WHITE);
        lbl_dueDate.setFont(new Font("Yu Gothic UI Semilight", Font.PLAIN, 20));
        
        lbl_issueError = new JLabel();
        lbl_issueError.setForeground(new Color(255, 0, 0));
        lbl_issueError.setFont(new Font("Yu Gothic UI Semilight", Font.PLAIN, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lbl_issueID, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lbl_bookName, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lbl_readerName, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lbl_issueDate, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(174, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(218, Short.MAX_VALUE)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        			.addGap(210))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(54, Short.MAX_VALUE)
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 417, GroupLayout.PREFERRED_SIZE)
        			.addGap(45))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblDueDate, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lbl_dueDate, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(174, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(76)
        			.addComponent(lbl_issueError, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(74)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 5, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lbl_issueID, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        			.addGap(52)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lbl_bookName, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        			.addGap(55)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lbl_readerName, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        			.addGap(63)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lbl_issueDate, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        			.addGap(48)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblDueDate, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lbl_dueDate, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        			.addGap(85)
        			.addComponent(lbl_issueError, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        
                jPanel2.setBackground(new java.awt.Color(203, 187, 139));
                
                        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
                        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
                        jLabel2.setText("Back");
                        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel2MouseClicked(evt);
                            }
                        });
                        
                                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                                jPanel2.setLayout(jPanel2Layout);
                                jPanel2Layout.setHorizontalGroup(
                                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addGap(22, 22, 22))
                                );
                                jPanel2Layout.setVerticalGroup(
                                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel2)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                );
        
        JLabel jLabel4_1 = new JLabel();
        jLabel4_1.setIcon(new ImageIcon(ReturnBook.class.getResource("/AddNewBookIcons/library.jpg")));
        jLabel4_1.setText("Issue ID:");
        jLabel4_1.setForeground(Color.WHITE);
        jLabel4_1.setFont(new Font("Yu Gothic UI Semilight", Font.PLAIN, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel4_1, GroupLayout.PREFERRED_SIZE, 319, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 516, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(panel_main, GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel4_1, GroupLayout.PREFERRED_SIZE, 677, Short.MAX_VALUE))
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        		.addComponent(panel_main, GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);
        setLocationRelativeTo(null);
        setSize(new java.awt.Dimension(1414, 751));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void returnMouseClicked (java.awt.event.MouseEvent evt){

		DatabaseBorrowing dbB = new DatabaseBorrowing();
    	DatabaseBook dbBook = new DatabaseBook();
    	
		if(getBorrowingDetails()) {
			if (dbB.updateBorrowingStatus(Integer.parseInt(txt_bookReference.getText()), Integer.parseInt(txt_readerID.getText()))
					&& dbBook.updateBookCountReturn(Integer.parseInt(txt_bookReference.getText()))) {
                JOptionPane.showMessageDialog(this, "Book returned successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Can't return the book");
            }
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_readerName;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_issueID;
    private javax.swing.JLabel lbl_issueDate;
    private javax.swing.JPanel panel_main;
    private javax.swing.JTextField txt_bookReference;
    private javax.swing.JTextField txt_readerID;
    private JButton return_Button;
    private JButton btnNewButton_1;
    private JLabel lbl_dueDate;
    private JLabel lbl_issueError;
    private JLabel lbl_Erro;
    private JLabel jLabel10;
}
