/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.Font;
import javax.swing.ImageIcon;
import java.awt.CardLayout;
import javax.swing.JLayeredPane;
import javax.swing.SwingConstants;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Dialog.ModalExclusionType;
/**
 *
* @author tina
 * @author stsof
 */
public class SignPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public SignPage() {
    	setAlwaysOnTop(true);
        initComponents();
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setMinimumSize(new java.awt.Dimension(1358, 702));
        setPreferredSize(new java.awt.Dimension(1358, 702));
        
        JPanel signUpPanel = new JPanel();
        
        signUpPanel.setBackground(new java.awt.Color(242, 238, 226));
        
        
        JPanel jPanel2 = new JPanel();
        jPanel2.setPreferredSize(new Dimension(1900, 70));
        jPanel2.setBackground(new Color(22, 54, 150));
        
        JLabel jLabel1 = new JLabel();
        jLabel1.setIcon(new ImageIcon(SignPage.class.getResource("/adminIcons/icons8_Library_32px.png")));
        jLabel1.setText("jLabel1");
        
        JPanel jPanel1 = new JPanel();
        jPanel1.setPreferredSize(new Dimension(5, 45));
        jPanel1.setBackground(Color.WHITE);
        GroupLayout gl_jPanel1 = new GroupLayout(jPanel1);
        gl_jPanel1.setHorizontalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 5, Short.MAX_VALUE)
        		.addGap(0, 5, Short.MAX_VALUE)
        );
        gl_jPanel1.setVerticalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 45, Short.MAX_VALUE)
        		.addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel1.setLayout(gl_jPanel1);
        
        JLabel jLabel24 = new JLabel();
        jLabel24.setText("Alice's Adventures In Javaland ");
        jLabel24.setForeground(Color.WHITE);
        jLabel24.setFont(new Font("Dialog", Font.PLAIN, 25));
        jLabel24.setBackground(Color.WHITE);
        
        JLabel jLabel3 = new JLabel();
        jLabel3.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		System.exit(0);
        	}
        });
        jLabel3.setText("X");
        jLabel3.setForeground(Color.WHITE);
        jLabel3.setFont(new Font("Dialog", Font.BOLD, 30));
        jLabel3.setBackground(Color.WHITE);
        GroupLayout gl_jPanel2 = new GroupLayout(jPanel2);
        gl_jPanel2.setHorizontalGroup(
        	gl_jPanel2.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel2.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel24, GroupLayout.PREFERRED_SIZE, 422, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 803, Short.MAX_VALUE)
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
        			.addGap(48))
        );
        gl_jPanel2.setVerticalGroup(
        	gl_jPanel2.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel2.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_jPanel2.createParallelGroup(Alignment.TRAILING)
        				.addGroup(gl_jPanel2.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel3)
        					.addComponent(jLabel24))
        				.addGroup(gl_jPanel2.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        			.addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2.setLayout(gl_jPanel2);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(signUpPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel2, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 1434, GroupLayout.PREFERRED_SIZE))
        			.addGap(894))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(signUpPanel, GroupLayout.PREFERRED_SIZE, 677, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        final JLabel passNotMatch = new JLabel("The passwords you entered don’t match up. Try again.");
        passNotMatch.setForeground(Color.RED);
        passNotMatch.setVisible(false);
        
        final JLabel adminAlready = new JLabel("This admin already exits.");
        adminAlready.setForeground(Color.RED);
        adminAlready.setVisible(false);
        
        JButton signUpButton = new JButton("Sign Up");
        signUpButton.setForeground(Color.WHITE);
        signUpButton.setPreferredSize(new Dimension(50, 30));
        signUpButton.setBackground(new java.awt.Color(22, 54, 150));
        signUpButton.setOpaque(true);
        signUpButton.setBorder(null);
        
        signUpButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		DatabaseAdmin dbAdmin = new DatabaseAdmin();
				
				if(dbAdmin.registedAdmin(emailTextField.getText())) {
					adminAlready.setVisible(true);
				}else {
					if(!ConfirmPassword.confirmPass(passwordTextField.getText(), confirmPasswordTextField.getText())) {
						passNotMatch.setVisible(true);
					}else {
						
						if(dbAdmin.newAdmin(new Admin(nameTextField.getText(),emailTextField.getText(),Integer.parseInt(phoneNoTextField.getText()) , passwordTextField.getText()))){
							LoginPage home = new LoginPage();
							home.setVisible(true);
				            dispose();
						}
					}
				}
        		
        	}
        });
        
        JButton cancelButton = new JButton("Log in");
        cancelButton.setForeground(new java.awt.Color(22, 54, 150));
        cancelButton.setFont(new Font("Dialog", Font.BOLD, 12));
        cancelButton.setBackground(new java.awt.Color(242, 238, 226));
        cancelButton.setOpaque(true);
        cancelButton.setBorder(null);
        
        cancelButton.setPreferredSize(new Dimension(50, 30));
        cancelButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		LoginPage home = new LoginPage();
                home.setVisible(true);
                dispose();
        	}
        });
        
        JPanel panelSign = new JPanel();
        panelSign.setBackground(new java.awt.Color(240, 227, 186));
        
        JLabel nameLabel = new JLabel("Name");
        nameLabel.setForeground((new java.awt.Color(22, 54, 150)));
        nameLabel.setFont(new Font("Dialog", Font.BOLD, 18));
        
        nameTextField = new JTextField();
        nameTextField.setColumns(14);
        nameTextField.setBackground(new java.awt.Color(240, 227, 186));
        nameTextField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 54, 150)));
        nameTextField.setForeground((new java.awt.Color(22, 54, 150)));
        nameTextField.setFont(new Font("Dialog", Font.PLAIN, 18));
        
       
       
        JLabel emailLabel = new JLabel("Email");
        emailLabel.setForeground((new java.awt.Color(22, 54, 150)));
        emailLabel.setFont(new Font("Dialog", Font.BOLD, 18));
        
         
         emailTextField = new JTextField();
         emailTextField.setColumns(14);
         emailTextField.setBackground(new java.awt.Color(240, 227, 186));
         emailTextField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 54, 150)));
         emailTextField.setForeground((new java.awt.Color(22, 54, 150)));
         emailTextField.setFont(new Font("Dialog", Font.PLAIN, 18));
         
         
         phoneNoTextField = new JTextField();
         phoneNoTextField.setColumns(14);
         phoneNoTextField.setBackground(new java.awt.Color(240, 227, 186));
         phoneNoTextField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 54, 150)));
         phoneNoTextField.setForeground((new java.awt.Color(22, 54, 150)));
         phoneNoTextField.setFont(new Font("Dialog", Font.PLAIN, 18));
         
       
         JLabel lblNewLabel_2 = new JLabel("Phone Number");
         lblNewLabel_2.setForeground((new java.awt.Color(22, 54, 150)));
         lblNewLabel_2.setFont(new Font("Dialog", Font.BOLD, 18));
         
         JLabel passwordLabel = new JLabel("Password");
         passwordLabel.setForeground((new java.awt.Color(22, 54, 150)));
         passwordLabel.setFont(new Font("Dialog", Font.BOLD, 18));
         
         JLabel confirmPasswordLabel = new JLabel("Confirm Password");
         confirmPasswordLabel.setForeground((new java.awt.Color(22, 54, 150)));
         confirmPasswordLabel.setFont(new Font("Dialog", Font.BOLD, 18));
         
         
         
         passwordTextField = new JPasswordField();
         passwordTextField.setColumns(14);
         passwordTextField.setBackground(new java.awt.Color(240, 227, 186));
         passwordTextField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 54, 150)));
         passwordTextField.setForeground((new java.awt.Color(22, 54, 150)));
         passwordTextField.setFont(new Font("Dialog",Font.PLAIN, 18));
         
         
         confirmPasswordTextField = new JPasswordField();
         confirmPasswordTextField.setColumns(14);
         confirmPasswordTextField.setBackground(new java.awt.Color(240, 227, 186));
         confirmPasswordTextField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 54, 150)));
         confirmPasswordTextField.setForeground((new java.awt.Color(22, 54, 150)));
         confirmPasswordTextField.setFont(new Font("Dialog", Font.PLAIN, 18));
         
         JLayeredPane layeredPane = new JLayeredPane();
         layeredPane.setBackground(new java.awt.Color(240, 227, 186));
         layeredPane.setLayer(panelSign, 1);
         
         GroupLayout gl_panelSign = new GroupLayout(panelSign);
         gl_panelSign.setHorizontalGroup(
         	gl_panelSign.createParallelGroup(Alignment.LEADING)
         		.addGroup(gl_panelSign.createSequentialGroup()
         			.addGap(37)
         			.addGroup(gl_panelSign.createParallelGroup(Alignment.LEADING)
         				.addComponent(nameLabel, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
         				.addComponent(emailLabel)
         				.addComponent(lblNewLabel_2)
         				.addComponent(passwordLabel)
         				.addComponent(confirmPasswordLabel))
         			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         			.addGroup(gl_panelSign.createParallelGroup(Alignment.LEADING)
         				.addComponent(confirmPasswordTextField, GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
         				.addComponent(nameTextField, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
         				.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, 307, GroupLayout.PREFERRED_SIZE)
         				.addComponent(phoneNoTextField, 307, 307, 307)
         				.addComponent(passwordTextField, GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
         			.addGap(23))
         		.addGroup(gl_panelSign.createSequentialGroup()
         			.addComponent(layeredPane, GroupLayout.PREFERRED_SIZE, 497, GroupLayout.PREFERRED_SIZE)
         			.addContainerGap(45, Short.MAX_VALUE))
         );
         gl_panelSign.setVerticalGroup(
         	gl_panelSign.createParallelGroup(Alignment.LEADING)
         		.addGroup(gl_panelSign.createSequentialGroup()
         			.addGroup(gl_panelSign.createParallelGroup(Alignment.LEADING)
         				.addGroup(gl_panelSign.createSequentialGroup()
         					.addGap(39)
         					.addComponent(nameLabel, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
         					.addPreferredGap(ComponentPlacement.UNRELATED)
         					.addComponent(emailLabel))
         				.addGroup(gl_panelSign.createSequentialGroup()
         					.addGap(31)
         					.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
         					.addPreferredGap(ComponentPlacement.UNRELATED)
         					.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)))
         			.addGap(18)
         			.addGroup(gl_panelSign.createParallelGroup(Alignment.LEADING)
         				.addComponent(lblNewLabel_2, Alignment.TRAILING)
         				.addComponent(phoneNoTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
         			.addGap(18)
         			.addGroup(gl_panelSign.createParallelGroup(Alignment.LEADING)
         				.addComponent(passwordLabel, Alignment.TRAILING)
         				.addComponent(passwordTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
         			.addGap(20)
         			.addGroup(gl_panelSign.createParallelGroup(Alignment.TRAILING)
         				.addComponent(confirmPasswordLabel)
         				.addComponent(confirmPasswordTextField, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
         			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         			.addComponent(layeredPane, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE))
         );
         panelSign.setLayout(gl_panelSign);
        
        JLabel lblNewLabel = new JLabel("SIGN UP");
        lblNewLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 60)); // NOI18N
        
        JLabel lblNewLabel_1 = new JLabel("Already a member?");
       
        
        
        GroupLayout gl_signUpPanel = new GroupLayout(signUpPanel);
        gl_signUpPanel.setHorizontalGroup(
        	gl_signUpPanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_signUpPanel.createSequentialGroup()
        			.addGap(434)
        			.addComponent(panelSign, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(452, Short.MAX_VALUE))
        		.addGroup(gl_signUpPanel.createSequentialGroup()
        			.addGap(552)
        			.addComponent(passNotMatch)
        			.addContainerGap())
        		.addGroup(gl_signUpPanel.createSequentialGroup()
        			.addContainerGap(643, Short.MAX_VALUE)
        			.addComponent(adminAlready)
        			.addGap(627))
        		.addGroup(Alignment.TRAILING, gl_signUpPanel.createSequentialGroup()
        			.addContainerGap(591, Short.MAX_VALUE)
        			.addGroup(gl_signUpPanel.createParallelGroup(Alignment.TRAILING)
        				.addGroup(gl_signUpPanel.createSequentialGroup()
        					.addComponent(lblNewLabel_1)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addComponent(signUpButton, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE))
        			.addGap(654))
        		.addGroup(gl_signUpPanel.createSequentialGroup()
        			.addGap(569)
        			.addComponent(lblNewLabel)
        			.addContainerGap(613, Short.MAX_VALUE))
        );
        gl_signUpPanel.setVerticalGroup(
        	gl_signUpPanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_signUpPanel.createSequentialGroup()
        			.addGap(65)
        			.addComponent(lblNewLabel)
        			.addGap(18)
        			.addComponent(panelSign, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE)
        			.addGap(21)
        			.addGroup(gl_signUpPanel.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel_1))
        			.addGap(18)
        			.addComponent(signUpButton, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(passNotMatch)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(adminAlready)
        			.addContainerGap(48, Short.MAX_VALUE))
        );
        signUpPanel.setLayout(gl_signUpPanel);
        getContentPane().setLayout(layout);
        
        setSize(new java.awt.Dimension(1414, 751));
        setLocationRelativeTo(null);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignPage().setVisible(true);
            }
        });
    }
    
    private JTextField emailTextField;
	private JTextField nameTextField;
	private JTextField phoneNoTextField;
	private JTextField passwordTextField;
	private JTextField confirmPasswordTextField;
	
}
