package jframe;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.Color;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;


/**
 *
 * @author tina
 * @author stsof
 */
//Page that displays all the borrowings (returned or not returned)
public class ViewRecords extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
	String book_name, author, genre;
	int book_reference, quantity;
	DefaultTableModel model;
	DBConnection db = new DBConnection();
	
	Color blue = new java.awt.Color(22, 54, 150);
	Color ligthB = new java.awt.Color(242, 238, 226);
	Color mediumB = new java.awt.Color(240, 227, 186);
	Color darkB = new java.awt.Color(203, 187, 139);
	
	
    public ViewRecords() {
        initComponents();
        setIssueBookDetailsToTable();
    }
    
    public void setIssueBookDetailsToTable() {
    	
    	DatabaseBorrowing dbB = new DatabaseBorrowing();
        
    	for(Borrowing borrow : dbB.selectAllBorrowing()) {
    		
    		Object[] obj = borrow.borrowingToVector3(borrow);
    		model = (DefaultTableModel) tbl_boDetails.getModel();
            model.addRow(obj);
    	} 	
    	
    }
    
    //Clear Data of the Table
    public void clearTable() {
    	DefaultTableModel model = (DefaultTableModel) tbl_boDetails.getModel();
    	model.setRowCount(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_boDetails = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1358, 702));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1358, 702));
        
      

        jPanel3.setBackground(ligthB);

        tbl_boDetails.setBackground(mediumB);
        tbl_boDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        tbl_boDetails.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        tbl_boDetails.setForeground(blue);
        tbl_boDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reader Name", "Book Tittle", "Start Date", "Delivered Date", "Deliver Deadline", "Status"
            }
        ));
        tbl_boDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_boDetails.setGridColor(blue);
        tbl_boDetails.setRowHeight(30);
        tbl_boDetails.setRowMargin(5);
        tbl_boDetails.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_boDetails.setSelectionForeground(blue);
        tbl_boDetails.setShowGrid(true);
        tbl_boDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bookDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_bookDetailsMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_boDetails);
        jScrollPane2.setBackground(mediumB);
        

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel11.setForeground(blue);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jLabel11.setText("Borrowing Record ");
        jLabel10 = new javax.swing.JLabel();
        
                jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 46)); // NOI18N
                jLabel10.setForeground(blue);
                jLabel10.setText("X");
                jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel10MouseClicked(evt);
                    }
                });
        
        jPanel2 = new JPanel();
        jPanel2.setBackground(new Color(203, 187, 139));
        
        jLabel2 = new JLabel();
        jLabel2.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
                HomePage home = new HomePage();
                home.setVisible(true);
                dispose();
        	}
        });
        jLabel2.setIcon(new ImageIcon(ViewRecords.class.getResource("/AddNewBookIcons/icons8_Rewind_48px.png")));
        jLabel2.setText("Back");
        jLabel2.setForeground(Color.WHITE);
        jLabel2.setFont(new Font("Yu Gothic UI Semilight", Font.PLAIN, 20));
        GroupLayout gl_jPanel2 = new GroupLayout(jPanel2);
        gl_jPanel2.setHorizontalGroup(
        	gl_jPanel2.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 143, Short.MAX_VALUE)
        		.addGroup(gl_jPanel2.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        			.addGap(22))
        );
        gl_jPanel2.setVerticalGroup(
        	gl_jPanel2.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 68, Short.MAX_VALUE)
        		.addGroup(gl_jPanel2.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel2)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2.setLayout(gl_jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        			.addGap(382)
        			.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 316, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 497, Short.MAX_VALUE)
        			.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        			.addGap(27))
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(220)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 930, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addGap(20)
        							.addComponent(jLabel10))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addGap(67)
        							.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)))
        					.addGap(113)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 411, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 1414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        setSize(new java.awt.Dimension(1414, 751));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void tbl_bookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookDetailsMouseClicked
        // TODO add your handling code here:
        int rowNumber = tbl_boDetails.getSelectedRow();
    	TableModel model = tbl_boDetails.getModel();
    		
  

    	/*
.setText(model.getValueAt(rowNumber, 0).toString());
    	txt_bookName.setText( model.getValueAt(rowNumber, 1).toString());
    	txt_authorName.setText( model.getValueAt(rowNumber, 2).toString());
    	txt_quantity.setText( model.getValueAt(rowNumber,3).toString());
    	*/
    	
    }//GEN-LAST:event_tbl_bookDetailsMouseClicked

    private void tbl_bookDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookDetailsMouseEntered

    	
    }//GEN-LAST:event_tbl_bookDetailsMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new ManageBooks().setVisible(true);
				} 
             catch (Exception e) {
                e.printStackTrace();
            }
            }
        });
    }
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_boDetails;
    private JPanel jPanel2;
    private JLabel jLabel2;
}
